### PR TITLE
use `Download` from the utils package instead of `PKGMAN_DownloadURL`

### PR DESCRIPTION
**Pull request by ThomasBreuer**
- call `Download` instead of `PKGMAN_DownloadURL`

- suggest utils >= 0.77 (version number to be confirmed) instead of curlInterface (then utils should suggest curlInterface);
  in fact, utils must become a needed package

- removed some tests that rely on individually chosen download methods

- removed `PKGMAN_DownloadURL`, `PKGMAN_DownloadCmds`, `PKGMAN_CurlIntReqVer`

(Removing `PKGMAN_CurlIntReqVer` also fixes the problem that in general it is not correct to assume that the info record for the loaded version of `PackageManager` is the first in the list `PackageInfo("PackageManager")`.

Some tests currently fail because download failures are detected earlier; if curlInterface is used then this is due to the new option `failOnError`, see gap-packages/curlInterface/pull/44.
I am not sure whether just the test results should be adjusted, or whether also the underlying code should be revised.

This pull request relies on gap-packages/utils/pull/48, which in turn relies on gap-packages/curlInterface/pull/44.

### CODE REVIEW

**Comment by fingolfin** [comment]
@ThomasBreuer somehow there is a conflict in `PackageInfo.g`. Maybe you didn't base your patch on the latest `master`?

**Comment by ThomasBreuer** [comment]
The current test failures are due to the fact that the utils package in version at least 0.77 (with the new `Download` function, see gap-packages/utils/pull/48) is a needed package. We have to wait for a release of utils before we can proceed with this pull request.

**Comment by james-d-mitchell** [comment]
Thanks for this @ThomasBreuer. I'm not in favour of increasing the dependencies of the `PackageManager` to include `utils` however. I'm using the `PackageManager` in continuous integration in GAP with no packages available (none, except `PackageManager` itself), and then using `PackageManager` to install the necessary packages for GAP (`primgrp`, `GAPDoc` etc). If I need to install `utils` before I can use `PackageManager`, then this just introduces another ad hoc step in getting GAP up and running.  Note that `curlinterface` is not a required package of the package manager, and it's possible to use the `PackageManager` without `curlinterface` installed. This PR makes `utils` the only `NeededPackage` of `PackageManager`. 

In principal, I see the point of the PR, but would rather that Issue #94 was resolved in a different way, and that the list of `NeededPackage`s for `PackageManager` stayed empty.

**Comment by ThomasBreuer** [comment]
@james-d-mitchell O.k., if you do not want to "outsource" the download functionality to another package then we cannot merge this pull request. An alternative would be to add the changes from gap-packages/utils/pull/48 to PackageManager.
On the other hand, there are quite a few other GAP packages which currently provide some download function, and which are likely to claim that PackageManager is an unwanted dependency.
Thus it looks as if the current collection of individual download functions in various packages will remain as it is.
(Or should the function get added to the code GAP system?)

**Comment by mtorpey** [comment]
I'm in agreement with @james-d-mitchell, in that I think it's highly desirable to keep PackageManager free of dependencies -- a major objective of this package is to be able to use it to bootstrap the whole package library, and any dependencies make that less effective.

I do agree, however, that a more consistent download style across packages would be good.  The GAP library seems like a good place for this, to avoid issues like this -- but I don't know how easy this is.

I'll close this for now, but thank you!

**Pull request closed without merging**
